classDiagram
  class OrderModel {
    customer_address : str
    customer_contact : int
    customer_name : str
    deliver_type : str
    items : list[OrderProductModel]
    order_number : int
    order_status : str
    order_type : str
    staff : str
    transection : str
    values
    add_item(item)
  }
  class OrderProductModel {
    base_referance : Optional[Product]
    extra_options : list[ProductOption]
    quality : int
    total_charge() float
  }
  class Product {
    addication_extra_options : list[ProductOption]
    full_price_value
    item_type : str
    kal : int
    name : str
    price_value : float
    rate : float
  }
  class ProductOption {
    extra_charge : float
    max_count : int
    min_count : int
    name : str
    option_kind : str
  }
