classDiagram
  class dummy_class {
  }
  class order_model {
  }
  class order_product_model {
  }
  class product {
  }
  class product_option {
  }
  order_product_model --> product
  order_product_model --> product_option
  product --> product_option
