"""empty message

Revision ID: 3fd4364d9d38
Revises: 5243613708a0
Create Date: 2023-05-12 10:37:49.038395

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3fd4364d9d38"
down_revision = "5243613708a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
