"""empty message

Revision ID: eb8a5565f420
Revises: 57a0ef4a0ef4
Create Date: 2023-04-11 09:25:21.751029

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb8a5565f420"
down_revision = "57a0ef4a0ef4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_receipt",
        "order_snapshot",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    op.drop_column("production_option", "_option_sets")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "production_option",
        sa.Column(
            "_option_sets", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "order_receipt",
        "order_snapshot",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    # ### end Alembic commands ###
