"""empty message

Revision ID: a13f78d1a3ed
Revises: 4933d23d50cc
Create Date: 2023-05-02 15:10:46.549108

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a13f78d1a3ed"
down_revision = "4933d23d50cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "op_order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("contact_type", sa.String(length=250), nullable=False),
        sa.Column("status", sa.String(length=250), nullable=False),
        sa.Column("deliver_type", sa.String(length=250), nullable=False),
        sa.Column("customer_name", sa.String(length=500), nullable=False),
        sa.Column("customer_contact", sa.Integer(), nullable=False),
        sa.Column("customer_address", sa.String(length=500), nullable=False),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("staff", sa.String(length=200), nullable=False),
        sa.Column("fk_transaction", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_transaction"],
            ["transaction.id"],
            name="fk_op_order_transaction_id_transaction",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ordprod",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("fk_base_referance_product", sa.Integer(), nullable=False),
        sa.Column("fk_order_refer", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_base_referance_product"],
            ["product.id"],
            name="fk_ordprod_product_id_base_referance",
        ),
        sa.ForeignKeyConstraint(
            ["fk_order_refer"], ["op_order.id"], name="fk_ordprod_op_order_id_for_order"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ordprodopt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("option", sa.String(length=500), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("charge", sa.Float(), nullable=False),
        sa.Column("fk_options_product", sa.Integer(), nullable=False),
        sa.Column("fk_order_product", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_options_product"],
            ["production_option.id"],
            name="fk_ordprodopt_production_option_id_option_referance",
        ),
        sa.ForeignKeyConstraint(
            ["fk_order_product"],
            ["production_option.id"],
            name="fk_ordprodopt_production_option_id_order_option_for",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ordprodopt")
    op.drop_table("ordprod")
    op.drop_table("op_order")
    # ### end Alembic commands ###
